version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    restart: unless-stopped

  web:
    build: .
    expose:
      - "5000"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONFAULTHANDLER=1
    depends_on:
      redis:
        condition: service_healthy
      worker:
        condition: service_started
    restart: unless-stopped

  worker:
    build: .
    command: celery -A celery_app.celery worker --loglevel=INFO --concurrency=1
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONFAULTHANDLER=1
      - C_FORCE_ROOT=true
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped
